# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170oF-Yb-EOlkMJ3XpE8QKbvj4JdrDmrB
"""

!pip install flask
!pip install pyngrok

from pyngrok import ngrok, conf

# Paste your token here
ngrok.set_auth_token("2xe5rHOfxpQrVKEhfT98oGhhhSI_5utRGPtaYirp33CqvZ5eX")

from flask import Flask, request, jsonify
from pyngrok import ngrok
import joblib
import numpy as np

# Load the model
model = joblib.load("cycle_predictor_model.pkl")

# Create the app
app = Flask(__name__)

@app.route("/")
def home():
    return "✅ Cycle Predictor API is running via pyngrok!"

@app.route("/predict", methods=["POST"])
def predict():
    try:
        data = request.json
        features = np.array([data["features"]])
        prediction = model.predict(features)
        return jsonify({
            "predicted_cycle_length": round(float(prediction[0]), 2)
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 400

# Start ngrok tunnel manually
public_url = ngrok.connect(5000)
print("🚀 Public URL:", public_url)

# Run Flask
app.run(port=5000)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# flask
# numpy
# joblib
#